# Generated by Django 3.0.5 on 2020-04-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('developer_last_name', models.CharField(max_length=100, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=100, verbose_name='Story Title')),
                ('estimated_story_time', models.DurationField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('time_estimated', models.DurationField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Sprint')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Story')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DurationField()),
                ('date', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Task')),
            ],
        ),
    ]
